language: python
env:
    - TOXENV=py27-req2
    - TOXENV=py33-req3
    - TOXENV=py34-req3
before_install:
    - sudo apt-get -qq install graphviz > /dev/null
    - travis_retry pip install tox
    - psql -U postgres -c "CREATE DATABASE test ENCODING 'UTF8';"
    - psql -U postgres test -c "CREATE SCHEMA test;"
script:
    - travis_retry tox
after_success:
    - coveralls