language: python
python:
    - "2.7"
before_install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - py.test
    - coverage run --source=eralchemy py.test
after_success:
    - coveralls